name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./hosting
        run: yarn --frozen-lockfile

      - name: Build
        working-directory: ./hosting
        run: yarn build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NUTRISNAP_96CAF }}'
          channelId: live
          projectId: nutrisnap-96caf
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
